/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pms;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class Customer_Invoice extends javax.swing.JFrame {

    private DefaultTableModel model;
    public Customer_Invoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jUpdate = new javax.swing.JButton();
        jremove = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jbatchno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jmcode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jqty = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        junitprice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jamount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jname = new javax.swing.JTextField();
        jADD = new javax.swing.JButton();
        jClear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(76, 99, 91));
        jPanel7.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 6, -1, 96));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Medicine");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 160, -1));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Supplier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 160, -1));

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Invoice");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 160, -1));

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 160, -1));

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("User");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 160, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 126, 205, 10));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Customer Invoice");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 645, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/icons/icons8-user-50.png"))); // NOI18N
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 96));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("User");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 43, -1, -1));

        jTable1.setBackground(new java.awt.Color(229, 229, 229));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BatchNo", "MCode", "Description", "Qty", "Unit Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 231, 697, 225));

        jUpdate.setBackground(new java.awt.Color(153, 153, 153));
        jUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jUpdate.setText("Update");
        jUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateActionPerformed(evt);
            }
        });
        jPanel7.add(jUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 488, -1, -1));

        jremove.setBackground(new java.awt.Color(153, 153, 153));
        jremove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jremove.setText("Remove");
        jremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jremoveActionPerformed(evt);
            }
        });
        jPanel7.add(jremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 488, -1, -1));

        jButton7.setBackground(new java.awt.Color(153, 153, 153));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setText("Reset");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 488, 99, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 487, 87, -1));

        jtotal.setBackground(new java.awt.Color(153, 153, 153));
        jtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel7.add(jtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 488, 130, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("BatchNo");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 73, -1));

        jbatchno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbatchno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbatchnoKeyPressed(evt);
            }
        });
        jPanel7.add(jbatchno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 220, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Mcode");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 83, -1));

        jmcode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmcodeKeyPressed(evt);
            }
        });
        jPanel7.add(jmcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 222, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Quantity");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 83, -1));

        jqty.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jqty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jqtyStateChanged(evt);
            }
        });
        jPanel7.add(jqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 71, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Unit price");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 83, -1));

        junitprice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        junitprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                junitpriceActionPerformed(evt);
            }
        });
        jPanel7.add(junitprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 71, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Amount");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 83, -1));

        jamount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamountActionPerformed(evt);
            }
        });
        jPanel7.add(jamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 71, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Name");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 60, -1));

        jname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel7.add(jname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 151, -1));

        jADD.setBackground(new java.awt.Color(153, 153, 153));
        jADD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jADD.setText("ADD");
        jADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jADDActionPerformed(evt);
            }
        });
        jPanel7.add(jADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 54, -1, -1));

        jClear.setBackground(new java.awt.Color(153, 153, 153));
        jClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jClear.setText("Clear");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });
        jPanel7.add(jClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 99, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/Photos/Stock2.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 710, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        medicine medi = new medicine();
        medi.show();

        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Supplier1 sup = new Supplier1();
        sup.show();

        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Report rep = new Report();
        rep.show();

        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        User_Account UAC = new User_Account();
        UAC.show();

        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Dashboard1 DB = new Dashboard1();
        DB.show();
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        jLabel2.setText(Pharmacy_Management_System.getUsername());
    }//GEN-LAST:event_formComponentShown

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
        // TODO add your handling code here:
        String batchno;
        String mcode ;
        String qty ;
        int i;
        int rows_affected =0;

        try {
            Connection con = Pharmacy_Management_System.getConnection();
            Statement stmt = con.createStatement();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            for ( i = 0; i < model.getRowCount(); i++) {
                batchno = model.getValueAt(i, 0).toString();
                mcode = model.getValueAt(i, 1).toString();
                qty = model.getValueAt(i, 3).toString();

                System.out.println(batchno+" "+mcode+"  "+qty);
                System.out.println(model.getRowCount());

                // Update stock table with adjusted quantity
                String updateQuery = "UPDATE stock SET qty = qty - " + qty + " WHERE mcode = '" + mcode + "' AND batchno = '" + batchno + "'";
                rows_affected = stmt.executeUpdate(updateQuery);

            }
            if(rows_affected ==1){
                JOptionPane.showMessageDialog(this, "Database updated");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            System.err.println("Error updating database: " + e.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jUpdateActionPerformed

    private void jremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jremoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int[] selectedRows = jTable1.getSelectedRows();

        for (int i = selectedRows.length - 1; i >= 0; i--) {//if multiple rows are selected it start from last selected row to first selected row
            model.removeRow(selectedRows[i]);
        }

        double sum = 0.0;

        for (int i = 0; i < model.getRowCount(); i++) {
            sum = sum+ Double.parseDouble(model.getValueAt(i, 5).toString());
            // Display the sum
            jtotal.setText(String.valueOf(sum));
        }
    }//GEN-LAST:event_jremoveActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtotal.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jbatchnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbatchnoKeyPressed
        // TODO add your handling code here:
        Connection con = null;
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String mcode = jmcode.getText();
            String batchno = jbatchno.getText();

            try {
                con = Pharmacy_Management_System.getConnection();
                Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

                ResultSet rs = stmt.executeQuery("SELECT s.s_price, d.name FROM stock s INNER JOIN drugs d ON s.mcode = d.mcode WHERE s.mcode = '" + mcode + "' AND s.batchno = '"+ batchno+"'");

                rs.beforeFirst();

                if(rs.next () == false)
                {
                    JOptionPane.showMessageDialog(this, "mcode or batchno invalied");
                }
                else{
                    double price=rs.getDouble(1);
                    String name=rs.getString(2);

                    junitprice.setText(String.valueOf(price));
                    jname.setText(name);

                }

                if (con != null) {
                    System.out.println("Connected to the database!");
                }
            } catch (SQLException e) {
                e.printStackTrace();
                System.err.println("Error connecting to the database: " + e.getMessage());
            }catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jbatchnoKeyPressed

    private void jmcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmcodeKeyPressed
        // TODO add your handling code here:

        Connection con = null;
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String mcode = jmcode.getText();
            String batchno = jbatchno.getText();

            try {
                con = Pharmacy_Management_System.getConnection();
                Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

                ResultSet rs = stmt.executeQuery("SELECT s.s_price, d.name FROM stock s INNER JOIN drugs d ON s.mcode = d.mcode WHERE s.mcode = '" + mcode + "' AND s.batchno = '"+ batchno+"'");

                rs.beforeFirst();

                if(rs.next () == false)
                {
                    JOptionPane.showMessageDialog(this, "mcode or batchno invalied");
                }
                else{
                    double price=rs.getDouble(1);
                    String name=rs.getString(2);

                    junitprice.setText(String.valueOf(price));
                    jname.setText(name);

                }

                if (con != null) {
                    System.out.println("Connected to the database!");
                }

            } catch (SQLException e) {
                e.printStackTrace();
                System.err.println("Error connecting to the database: " + e.getMessage());

            }catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jmcodeKeyPressed

    private void jqtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jqtyStateChanged
        // TODO add your handling code here:
        int q_qty =  (int)jqty.getValue();

        double price = Double.parseDouble(junitprice.getText());

        double amount = q_qty * price;

        jamount.setText(String.valueOf(amount));
    }//GEN-LAST:event_jqtyStateChanged

    private void jADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jADDActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        String batchno = jbatchno.getText();
        String code = jmcode.getText();
        String qty =jqty.getValue().toString();
        String price = junitprice.getText(); // Assuming pprice is a JTextField or similar component
        String amount = jamount.getText() ;
        String name = jname.getText();

        if(qty.isEmpty() || price.isEmpty() || amount.isEmpty() || name.isEmpty()|| batchno.isEmpty() )
        {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");

        }else{
            // Add a new row to the table
            model.addRow(new Object[]{batchno,code, name,qty,price,amount});

            jbatchno.setText("");
            jmcode.setText("");
            jqty.setValue(0);
            jname.setText("");
            junitprice.setText("");
            jamount.setText("");
            jname.setText("");

            double sum = 0.0;
            for (int i = 0; i < model.getRowCount(); i++) {
                sum = sum+ Double.parseDouble(model.getValueAt(i, 5).toString());

                // Display the sum

                jtotal.setText(String.valueOf(sum));
            }
        }
    }//GEN-LAST:event_jADDActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        // TODO add your handling code here:
        jmcode.setText("");
        jbatchno.setText("");
        jqty.setValue(0);
        jname.setText("");
        junitprice.setText("");
        jamount.setText("");
        jname.setText("");
    }//GEN-LAST:event_jClearActionPerformed

    private void junitpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_junitpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_junitpriceActionPerformed

    private void jamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Customer_Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jADD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jClear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jUpdate;
    private javax.swing.JTextField jamount;
    private javax.swing.JTextField jbatchno;
    private javax.swing.JTextField jmcode;
    private javax.swing.JTextField jname;
    private javax.swing.JSpinner jqty;
    private javax.swing.JButton jremove;
    private javax.swing.JTextField jtotal;
    private javax.swing.JTextField junitprice;
    // End of variables declaration//GEN-END:variables
}
